name: build

on:
  push:
    branches:
      - 'add-onboarding-flow'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    timeout-minutes: 60
  
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run Build
        timeout-minutes: 20
        run: pnpm build

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and Push Image (ghcr.io)
        id: build-image-ghcr
        run: |
          podman build -t ghcr.io/soniasandler/podman-desktop-redhat-account-ext-builder:next . -f ./build/Containerfile.builder
          podman build -t ghcr.io/soniasandler/podman-desktop-redhat-account-ext:next . -f ./build/Containerfile
          podman push ghcr.io/soniasandler/podman-desktop-redhat-account-ext:next
